name: 同期

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v3

      - name: Server1 用の SSH キーを設定
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_SERVER1 }}

      - name: Server1 にデプロイ
        run: |
          echo "Server1 にファイルをコピー中..."
          scp -r ./* ${{ secrets.SERVER_USER }}@${{ secrets.SERVER1_HOST }}:~/echo-bot/
          echo "Server1 で update.sh を実行中..."
          ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER1_HOST }} '~/echo-bot/update.sh'

      - name: Server2 用の SSH キーを設定
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_SERVER2 }}

      - name: Server2 にデプロイ
        run: |
          echo "Server2 にファイルをコピー中..."
          scp -r ./* ${{ secrets.SERVER_USER }}@${{ secrets.SERVER2_HOST }}:~/echo-bot/
          echo "Server2 で update.sh を実行中..."
          ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER2_HOST }} '~/echo-bot/update.sh'
