name: アップデート検出

on:
  push:
    branches:
      - main
    paths:
      - '**/*'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Execute update script
      run: |
        bash ./update.sh
