name: Update and Deploy Echo-Bot

on:
  push:
    branches:
      - main
    paths:
      - '**/*'

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run update check script
      run: |
        bash $HOME/update_check.sh
